### ISSUE TITLE
追加機能・追加ページ案募集

### ISSUE THREAD

**Issue by ryo-ponsan** [greenGitWorkShop/task1#10]
アイデア募集します。
なんでも大丈夫ですので思いついたらお気軽にこちらに書き込んでいってください。
やりたいこと・挑戦したいことベースでも大丈夫です。
トップページ出来た段階(明日or明後日夜?)で、アイデアを基にみなさんで議論できたらと思います！

ただし
- カフェに関係するもの（間接的にでも。自由度は高く全く関係のないコンテンツでなければ問題ありません。）
- トップページへの更なる追加も有り

**Comment by ryo-ponsan** [comment]
- コーヒー占い機能orページ（本日のあなたと相性のいいコーヒー豆は？） 
   ボタン押すとランダムで画像と説明つきポップアップ表示
- スライダーの画像をクリックすると、紐づいたページへ移動（ex特集ページ）

**Comment by yu-zakimiya** [comment]
・各メニューページ(クリックするとポップアップでメニューの詳細が表示される)

・フッター(各種SNSアイコン 全ページ共通で良いのでは？)

・コーヒー占い良いですね！🙌

**Comment by ryo-ponsan** [comment]
案いったん固まりましたのでCloseします
